# Generated by Django 4.2.26 on 2025-11-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpol', '0002_alter_partner_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('waste_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
